### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by bstro** [wavebeem/bread-n-butter#32]
Hi there; hoping none of this comes across with an entitled tone, I'm just looking for some signal about the status of this project. I'm building a side-project and looking around for promising typescript combinator libraries and I stumbled across this while looking at https://github.com/jneen/parsimmon/issues/230. Is this library still being worked on?

**Comment by wavebeem** [comment]
Hi @bstro

The status of this project is "it does everything I need it to do already", essentially

As for Parsimmon v2, the status on that is "I don't have the energy to work on this right now"

Most likely Parsimmon v2 will be incredibly similar or nearly identical to bread-n-butter.

A tool like parser combinators doesn't really need to be updated frequently, in my opinion. Parsimmon became bloated, and I'd rather encourage folks to make companion libraries, rather than incorporating every possible combinator into one big library (look at how huge lodash is these days...).

**Comment by wavebeem** [comment]
If you want to use bnb in your project, I think you should. When Parsimmon v2 eventually arrives, I think it should be a simple migration, mostly renaming things, for most uses.

**Comment by bstro** [comment]
Thanks @wavebeem! I appreciate your reply. I like the look of bnb's api and I'm gonna give it a shot!

**Comment by stefnotch** [comment]
For the record, I've been using this library to write a [math and boolean algebra parser](https://github.com/tuwien2020/tgi-pages/blob/c19027ecdfe650e9336629f44213203e287e6edf/src/math/math-parsing.ts#L1). It even gets the exponent rules right! The API is really nice and the library has given me zero issues so far.

Glad to hear that it wasn't just my impression and that this library is indeed really stable.
